name: Build Service

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: Release tag
        required: true
      environment:
        type: environment
        description: Select the environment
  push:
    branches-ignore:
      - "**"
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # - name: Set Repo Envs
    #   run: |
    #     REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
    #     echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV
    #     echo "docker_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV

    # - name: Checkout the repo
    #   uses: actions/checkout@v2
    #   with:
    #     #repository: $GITHUB_REPOSITORY
    #     path: ${{ env.git_repo_name }}
    #     fetch-depth: 0

    - name: set version Prod
      if: ${{ github.event.inputs.environment == 'production' }}
      run: |
        VERSION="${{ github.event.inputs.release-tag }}"
        echo "${VERSION}"


    - name: set version Dev
      if: ${{ github.event.inputs.environment == 'dev' }}
      run: |
        VERSION="${{ github.event.inputs.release-tag }}"
        echo "${VERSION}"
    # - name: commit-tag-build
    #   env:
    #     TAG: ${{ env.TAG }}
    #     SHA: ${{ env.SHA }}
    #   run: |
    #     git -C ${{ env.git_repo_name }} config user.name "GitHub Actions Bot"
    #     git -C ${{ env.git_repo_name }} config user.email "<>"
    #     git -C ${{ env.git_repo_name }} tag "${TAG}" ${SHA} || true
    #     git -C ${{ env.git_repo_name }} push --tags || true

        
