name: Build Service
on:
  workflow_dispatch:
    inputs:    
      release-tag:
        description: Release tag
        required: true
  push:
    #branches-ignore:
    branches:
      - "**"
      
jobs:
  build:
    if: ${{ (github.event.inputs.release-tag) }} 
    runs-on: ubuntu-latest
    steps:
    - name: Set Repo Envs
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
        echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV
        echo "docker_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV

    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        #repository: $GITHUB_REPOSITORY
        path: ${{ env.git_repo_name }}
        # fetch-depth: 0
        ref: ${GITHUB_REF}

    - name: commit-tag-build
      run: |
        git -C ${{ env.git_repo_name }} config user.name "GitHub Actions Bot"
        git -C ${{ env.git_repo_name }} config user.email "<>"
        git -C ${{ env.git_repo_name }} tag ${{ github.event.inputs.release-tag }} || true
        git -C ${{ env.git_repo_name }} push --tags || true

        
