name: Build Service

on:
  repository_dispatch:
    types:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Repo Envs
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
        echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV
        echo "docker_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV

    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        #repository: $GITHUB_REPOSITORY
        path: ${{ env.git_repo_name }}
        fetch-depth: 0

    - name: set version
      run: |
        GITVERSION=${{ github.event.client_payload.TAG }}
        SHA=${{ github.event.client_payload.TAG }}
        echo "gitversion=${GITVERSION}" | tee -a $GITHUB_ENV
        echo "sha=${SHA}" | tee -a $GITHUB_ENV

    - name: commit-tag-build
      env:
        TAG: ${{ env.gitversion }}
        SHA: ${{ env.sha }}
      run: |
        git -C ${{ env.git_repo_name }} config user.name "GitHub Actions Bot"
        git -C ${{ env.git_repo_name }} config user.email "<>"
        git -C ${{ env.git_repo_name }} tag "${TAG}" ${SHA} || true
        git -C ${{ env.git_repo_name }} push --tags || true

        
