name: Service test
on:
  workflow_dispatch:
    inputs:    
      release-tag:
        description: Release tag
     #   required: true
  push:
    #branches-ignore:
    branches:
      - "**"
    tags:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set Repo Envs
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          #repository: $GITHUB_REPOSITORY
          path: ${{ env.git_repo_name }}
          fetch-depth: 0

      - name: prep if tag
        id: prep
        run: |
          TAG=$(git -C ${{ env.git_repo_name }} describe --tags `git -C ${{ env.git_repo_name }} rev-list --tags --max-count=1`)
          echo ::set-output name=pre-tags::${TAG}
      - name: backup if no tag
        if: ${{ failure() }}
        id: bu-prep
        run: | 
          TAG=0.0.0
          echo ::set-output name=pre-tags::${TAG}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Calc tags
        if: ${{ always() }}
        id: calc
        run: | 
          npm install -g semver
          TAG=${{ steps.prep.outputs.pre-tags }}
          if [[ -z ${TAG} ]]; then
            log=$(git -C ${{ env.git_repo_name }} log --pretty=oneline)
            TAG=${{ steps.bu-prep.outputs.pre-tags }}
          else
            log=$(git -C ${{ env.git_repo_name }} log $TAG..HEAD --pretty=oneline)
          fi
          case "$log" in
              *#major* ) new=$(semver bump major $TAG);;
              *#patch* ) new=$(semver bump patch $TAG);;
              * ) new=$(semver bump minor $TAG);;
          esac
          commit=$(git -C ${{ env.git_repo_name }} rev-parse HEAD)
          echo log is: $log
          echo t is: $TAG
          echo new is $new
          echo commit is: $commit
          echo ::set-output name=tags::${new}
          echo ::set-output name=sha::${commit}

      - name: test starts here
        run: |
          echo started test

      - name: dispatch build
        run: |
          TAG=${{ steps.calc.outputs.tags }}
          SHA=${{ steps.calc.outputs.sha }}
          curl   \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mondbev1/${{ env.git_repo_name }}/dispatches \
          -d '{"event_type": "build", "client_payload": {"SHA": "${sha}", "TAG": "${TAG}"}}'
